version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install G++
          command: apt-get install g++ make

      - run:
          name: Build all
          command: make all